# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flow.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'flow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflow.proto\x12\x06\x66lowpb\"\x84\x01\n\x07\x46lowRaw\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.flowpb.FlowRaw.FlowType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04time\x18\x03 \x01(\x04\x12\x11\n\thost_name\x18\x04 \x01(\x04\"\"\n\x08\x46lowType\x12\t\n\x05SFLOW\x10\x00\x12\x0b\n\x07NETFLOW\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOWRAW']._serialized_start=23
  _globals['_FLOWRAW']._serialized_end=155
  _globals['_FLOWRAW_FLOWTYPE']._serialized_start=121
  _globals['_FLOWRAW_FLOWTYPE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
