

apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-teste-python
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: viniciusdossantos21/flow-processor:0.0.3
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/spark-processor/src/teste_spark.py 
  sparkVersion: 3.5.3
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    instances: 2
    cores: 1
    memory: 512m

